"use client";

import { useRouter } from "next/navigation";
import { useState, useTransition, type FormEvent, type ReactNode } from "react";
import type { BankTransaction, Collection, Payment, Run, Tenant, Vendor } from "@/lib/data/types";
import { captureBankLine, captureCollection, capturePayment, createRun, createTenant, createVendor } from "@/lib/actions/capture";
import { clearPayment, matchCollection, reconcileRun } from "@/lib/actions/matching";

type Props = { runs: Run[]; tenants: Tenant[]; vendors: Vendor[]; activeRun: Run | null; collections: Collection[]; payments: Payment[]; bankLines: BankTransaction[] };
type Action = (data: FormData) => Promise<void>;
const money = (n: number) => new Intl.NumberFormat("en-MY", { style: "currency", currency: "MYR", maximumFractionDigits: 2 }).format(Number(n) || 0);
const today = () => new Date().toLocaleDateString("en-CA");
const monthLabel = (value: string) => new Date(`${value.slice(0, 7)}-02T00:00:00`).toLocaleDateString("en-MY", { month: "long", year: "numeric" });

function Modal({ title, close, children }: { title: string; close: () => void; children: ReactNode }) {
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) close(); }}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div className="modal-head"><h2 id="modal-title">{title}</h2><button className="icon-button" onClick={close} aria-label="Close">×</button></div>{children}</section></div>;
}

function ActionForm({ action, close, children, submit, className }: { action: Action; close?: () => void; children: ReactNode; submit: string; className?: string }) {
  const router = useRouter();
  const [pending, start] = useTransition();
  const [error, setError] = useState("");
  function onSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError("");
    const form = new FormData(event.currentTarget);
    start(async () => { try { await action(form); close?.(); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Something went wrong. Please try again."); } });
  }
  return <form onSubmit={onSubmit} className={className ?? "form-stack"}>{children}{error && <p className="form-error" role="alert">{error}</p>}<button className="button button-primary" type="submit" disabled={pending}>{pending ? "Saving…" : submit}</button></form>;
}

function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="field"><span>{label}</span>{children}</label>; }
function Status({ value }: { value: string }) { return <span className={`status status-${value}`}>{value.replaceAll("_", " ")}</span>; }

export default function Workspace({ runs, tenants, vendors, activeRun, collections, payments, bankLines }: Props) {
  const router = useRouter();
  const [modal, setModal] = useState<string | null>(null);
  const [reconError, setReconError] = useState("");
  const [pending, start] = useTransition();
  const close = () => setModal(null);
  const sum = (rows: { amount: number }[]) => rows.reduce((total, row) => total + Number(row.amount), 0);
  const totalCredit = bankLines.filter((line) => line.direction === "credit").reduce((total, line) => total + Number(line.amount), 0);
  const totalDebit = bankLines.filter((line) => line.direction === "debit").reduce((total, line) => total + Number(line.amount), 0);
  const ledgerNet = sum(collections) - sum(payments);
  const variance = Math.round(((totalCredit - totalDebit - ledgerNet) + Number.EPSILON) * 100) / 100;
  const hasOpenItems = collections.some((row) => row.status !== "matched") || payments.some((row) => row.status !== "cleared") || bankLines.some((line) => line.status === "unmatched");
  const readyToReconcile = variance === 0 && !hasOpenItems;
  const open = activeRun?.status === "open";
  const unmatchedDebits = bankLines.filter((line) => line.direction === "debit" && line.status === "unmatched");
  const alreadyReconciled = activeRun?.status === "reconciled" || activeRun?.status === "locked";
  const settledItems = collections.filter((row) => row.status === "matched").length + payments.filter((row) => row.status === "cleared").length;
  const ledgerItems = collections.length + payments.length;
  const progress = ledgerItems ? Math.round((settledItems / ledgerItems) * 100) : 0;
  const reviewCount = collections.filter((row) => row.status !== "matched").length + payments.filter((row) => row.status !== "cleared").length + bankLines.filter((line) => line.status === "unmatched").length;
  const exactCredits = bankLines.filter((line) => line.direction === "credit" && line.status === "unmatched");
  const bankNet = totalCredit - totalDebit;

  function submitReconciliation() {
    if (!activeRun) return;
    setReconError("");
    const form = new FormData(); form.set("run_id", activeRun.id);
    start(async () => { try { await reconcileRun(form); router.refresh(); } catch (error) { setReconError(error instanceof Error ? error.message : "Could not reconcile this run."); } });
  }

  function runCollectionMatch(collectionId: string) {
    if (!activeRun) return;
    setReconError("");
    const form = new FormData(); form.set("run_id", activeRun.id); form.set("collection_id", collectionId);
    start(async () => { try { await matchCollection(form); router.refresh(); } catch (error) { setReconError(error instanceof Error ? error.message : "Could not match collection."); } });
  }

  return <div className="app-shell">
    <header className="topbar"><a href="/" className="brand"><span className="brand-mark">↗</span><span>LedgerFlow</span></a><div className="topbar-center"><span className="workspace-switch"><span className="workspace-avatar">SP</span><span><strong>Selangor Properties</strong><small>Operating workspace</small></span><span className="chevron">⌄</span></span><nav className="desktop-nav" aria-label="Reconciliation sections"><a href="#overview">Reconcile</a><a href="#ledger">Ledger</a><a href="#statement">Bank feed</a></nav></div><div className="top-actions"><button className="button button-outline top-people" onClick={() => setModal("people")}>Contacts</button><span className="avatar-small" aria-label="Finance team">FM</span></div></header>
    <main className="main-area" id="overview">
      <div className="page-content">
        <div className="page-heading"><div><div className="eyebrow">FINANCE OPERATIONS <span>·</span> MONTHLY CLOSE</div><h1>Reconciliation</h1><p className="subheading">Review statement lines against your ledger and close the month.</p></div><div className="heading-actions"><label className="run-select-label" htmlFor="run-select">Reconciliation period</label><select id="run-select" className="run-select" value={activeRun?.id ?? ""} onChange={(event) => router.push(event.target.value ? `/?run=${event.target.value}` : "/")}><option value="" disabled>Select a month</option>{runs.map((run) => <option key={run.id} value={run.id}>{monthLabel(run.period_month)}{run.status !== "open" ? ` · ${run.status}` : ""}</option>)}</select><button className="button button-outline" onClick={() => setModal("run")}>＋ New run</button></div></div>
        {!activeRun ? <section className="empty-state"><div className="empty-icon">▦</div><h2>Start your first reconciliation</h2><p>Create a monthly run to record rent collections, vendor payments, and bank statement lines.</p><button className="button button-primary" onClick={() => setModal("run")}>＋ Create a run</button></section> : <>
        <section className="run-banner" aria-label="Reconciliation progress"><div className="summary-meta"><span className="period-chip">{monthLabel(activeRun.period_month)}</span><Status value={activeRun.status}/><span className="summary-source">Statement entered manually</span></div><div className="progress-heading"><div><strong>{progress}%</strong><span>ledger entries matched or cleared</span></div><small>{settledItems} of {ledgerItems} entries complete</small></div><div className="progress-track"><span style={{ width: `${progress}%` }}/></div><div className={`variance-callout ${variance === 0 ? "variance-balanced" : ""}`}><span className="variance-message"><span className="variance-icon">{variance === 0 ? "✓" : "!"}</span><span>{variance === 0 ? hasOpenItems ? "No amount difference yet · items still need matching" : "All ledger and bank totals are in balance" : <>Difference: <strong>{money(variance)}</strong></>}</span></span>{reviewCount > 0 && <a href="#review">Review {reviewCount} open items <span>→</span></a>}</div></section>
        {reconError && <div className="inline-error" role="alert">{reconError}</div>}
        <section className="balance-summary" aria-label="Bank and ledger totals"><article><div className="balance-label"><span>Bank feed · net activity</span><Status value={bankLines.length ? "entered" : "empty"}/></div><strong>{money(bankNet)}</strong><small>{bankLines.length} statement lines · credits {money(totalCredit)} · debits {money(totalDebit)}</small></article><article><div className="balance-label"><span>General ledger · net activity</span><span className="ledger-state">{ledgerItems} entries</span></div><strong>{money(ledgerNet)}</strong><small>Collections {money(sum(collections))} · payments {money(sum(payments))}</small></article><div className="net-variance"><span>Net ledger difference</span><strong className={variance === 0 ? "net-balanced" : "net-unbalanced"}>{money(variance)}{variance !== 0 && ` · ${reviewCount} open`}</strong></div></section>
        <nav className="section-tabs" aria-label="Jump to reconciliation section"><a className="tab-active" href="#review">Needs review <span>{reviewCount}</span></a><a href="#ledger">Ledger <span>{ledgerItems}</span></a><a href="#statement">Bank feed <span>{bankLines.length}</span></a></nav>
        <section className="matching-queue" id="review"><div className="queue-heading"><div><h2>Needs review</h2><p>Match collected rent and clear vendor payments against statement lines.</p></div><div className="queue-actions"><button className="button button-outline" onClick={() => setModal("collection")} disabled={!open}>＋ Collection</button><button className="button button-outline" onClick={() => setModal("payment")} disabled={!open}>＋ Payment</button><button className="button button-primary" onClick={() => setModal("bank")} disabled={!open}>＋ Statement line</button></div></div>
          {collections.filter((row) => row.status !== "matched").length + payments.filter((row) => row.status !== "cleared").length === 0 ? <div className="queue-empty"><span>✓</span><div><strong>All ledger entries are settled</strong><small>{bankLines.some((line) => line.status === "unmatched") ? "Check the bank feed below for unmatched statement lines." : "Your collections and vendor payments are matched."}</small></div></div> : <div className="match-list">
            {collections.filter((row) => row.status !== "matched").map((row) => { const bankLine = exactCredits.find((line) => Number(line.amount) === Number(row.amount)); const tenant = tenants.find((item) => item.id === row.tenant_id); return <article className="match-card" key={row.id}><div className="match-card-top"><Status value={row.status}/><span className="match-reference">Tenant collection · {new Date(`${row.collection_date}T00:00:00`).toLocaleDateString("en-MY", { day: "2-digit", month: "short" })}</span></div><div className="match-pair"><div className="match-side"><span className="match-overline">BANK FEED {bankLine ? "· EXACT AMOUNT" : "· WAITING FOR CREDIT"}</span><strong>{bankLine?.description || (bankLine ? "Matching bank credit" : "No exact credit found")}</strong><small>{bankLine ? new Date(`${bankLine.txn_date}T00:00:00`).toLocaleDateString("en-MY", { day: "2-digit", month: "short", year: "numeric" }) : "Add or check the statement below"}</small><b className="match-money income-money">+{money(row.amount)}</b></div><span className={`match-link ${bankLine ? "linked" : "unlinked"}`}>{bankLine ? "↔" : "···"}</span><div className="match-side match-side-right"><span className="match-overline">TENANT LEDGER</span><strong>{row.tenants?.name ?? "Unassigned tenant"}</strong><small>Expected {money(tenant?.expected_monthly ?? 0)} / month</small><b className="match-money">+{money(row.amount)}</b></div></div>{(row.status === "short" || row.status === "excess") && <div className="match-note">This amount differs from the tenant’s expected monthly rent. Review the amount before closing the run.</div>}<div className="match-actions">{open && row.status === "pending" ? <button className="button button-primary" disabled={pending} onClick={() => runCollectionMatch(row.id)}>{pending ? "Working…" : "Compare & match collection"}</button> : <span className="match-hint">{row.status === "short" || row.status === "excess" ? "Amount review required" : "Run closed"}</span>}</div></article>; })}
            {payments.filter((row) => row.status !== "cleared").map((row) => { const bankLine = unmatchedDebits.find((line) => Number(line.amount) === Number(row.amount)); return <article className="match-card" key={row.id}><div className="match-card-top"><Status value={row.status}/><span className="match-reference">Vendor payment · {new Date(`${row.payment_date}T00:00:00`).toLocaleDateString("en-MY", { day: "2-digit", month: "short" })}</span></div><div className="match-pair"><div className="match-side"><span className="match-overline">BANK FEED {bankLine ? "· EXACT AMOUNT" : "· WAITING FOR DEBIT"}</span><strong>{bankLine?.description || "No exact debit found"}</strong><small>{bankLine ? new Date(`${bankLine.txn_date}T00:00:00`).toLocaleDateString("en-MY", { day: "2-digit", month: "short", year: "numeric" }) : "Add or check the statement below"}</small><b className="match-money">−{money(row.amount)}</b></div><span className={`match-link ${bankLine ? "linked" : "unlinked"}`}>{bankLine ? "↔" : "···"}</span><div className="match-side match-side-right"><span className="match-overline">VENDOR LEDGER</span><strong>{row.vendors?.name ?? "Unassigned vendor"}</strong><small>{row.reference || "Vendor payment"}</small><b className="match-money expense-money">−{money(row.amount)}</b></div></div><div className="match-actions">{open && <button className="button button-primary" onClick={() => setModal(`clear:${row.id}`)}>Choose debit &amp; clear payment</button>}</div></article>; })}
          </div>}
        </section>
        <section className="activity-summary" aria-label="Ledger totals"><Metric title="Tenant collections" value={money(sum(collections))} icon="↓" tone="mint" detail={`${collections.length} ledger entries`}/><Metric title="Vendor payments" value={money(sum(payments))} icon="↑" tone="blue" detail={`${payments.length} ledger entries`}/><Metric title="Bank credits" value={money(totalCredit)} icon="↙" tone="mint" detail={`${bankLines.filter((x) => x.direction === "credit").length} statement lines`}/><Metric title="Bank debits" value={money(totalDebit)} icon="↗" tone="amber" detail={`${bankLines.filter((x) => x.direction === "debit").length} statement lines`}/></section>
        <section className="ledger-card" id="ledger"><div className="section-heading"><div><div className="section-title-row"><h2>General ledger</h2><span className="count-pill">{collections.length + payments.length} entries</span></div><p>Tenant income and vendor expenses for {monthLabel(activeRun.period_month)}.</p></div><div className="ledger-buttons"><button className="button button-outline" onClick={() => setModal("collection")} disabled={!open}>＋ Collection</button><button className="button button-dark" onClick={() => setModal("payment")} disabled={!open}>＋ Payment</button></div></div>
        <div className="table-wrap"><table><thead><tr><th>DESCRIPTION</th><th>DATE</th><th>TYPE</th><th>AMOUNT</th><th>STATUS</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>
          {collections.map((row) => <tr key={row.id}><td><div className="entry-name"><span className="entry-icon income">↓</span><span><strong>{row.tenants?.name ?? "Unassigned tenant"}</strong><small>{row.source || row.note || "Tenant collection"}</small></span></div></td><td className="date-cell">{new Date(`${row.collection_date}T00:00:00`).toLocaleDateString("en-MY", { day: "2-digit", month: "short", year: "numeric" })}</td><td><span className="type-label">Collection</span></td><td className="amount-positive">+{money(row.amount)}</td><td><Status value={row.status}/></td><td>{open && row.status === "pending" && <button className="table-action" disabled={pending} onClick={() => { const form = new FormData(); form.set("run_id", activeRun.id); form.set("collection_id", row.id); start(async () => { try { await matchCollection(form); router.refresh(); } catch (e) { setReconError(e instanceof Error ? e.message : "Could not match collection."); } }); }}>{pending ? "Working…" : "Match"}</button>}{open && row.status !== "pending" && <span className="matched-amount">{money(row.matched)} matched</span>}</td></tr>)}
          {payments.map((row) => <tr key={row.id}><td><div className="entry-name"><span className="entry-icon expense">↑</span><span><strong>{row.vendors?.name ?? "Unassigned vendor"}</strong><small>{row.reference || "Vendor payment"}</small></span></div></td><td className="date-cell">{new Date(`${row.payment_date}T00:00:00`).toLocaleDateString("en-MY", { day: "2-digit", month: "short", year: "numeric" })}</td><td><span className="type-label">Payment</span></td><td className="amount-negative">−{money(row.amount)}</td><td><Status value={row.status}/></td><td>{open && row.status === "outstanding" && <button className="table-action" disabled={pending} onClick={() => setModal(`clear:${row.id}`)}>Clear</button>}{!open && <span className="matched-amount">{row.status === "cleared" ? "Bank matched" : "Open item"}</span>}</td></tr>)}
        </tbody></table>{collections.length + payments.length === 0 && <div className="table-empty"><div className="empty-icon">▤</div><strong>No ledger entries yet</strong><span>Add a tenant collection or vendor payment to get started.</span><div><button className="button button-outline" onClick={() => setModal("collection")} disabled={!open}>＋ Add collection</button><button className="button button-outline" onClick={() => setModal("payment")} disabled={!open}>＋ Add payment</button></div></div>}</div>
        </section>
        <section className="bank-card" id="statement"><div className="section-heading"><div><div className="section-title-row"><h2>Bank statement</h2><span className="count-pill">{bankLines.length} lines</span></div><p>Match collections and clear payments against your statement.</p></div><button className="button button-outline" onClick={() => setModal("bank")} disabled={!open}>＋ Add bank line</button></div>
          {bankLines.length === 0 ? <div className="bank-empty"><span className="empty-icon">⇄</span><span><strong>No statement lines yet</strong><small>Add the credits and debits from your bank statement for a complete reconciliation.</small></span></div> : <div className="bank-list">{bankLines.map((line) => <div className="bank-row" key={line.id}><span className={`entry-icon ${line.direction === "credit" ? "income" : "expense"}`}>{line.direction === "credit" ? "↓" : "↑"}</span><span className="bank-description"><strong>{line.description || (line.direction === "credit" ? "Bank credit" : "Bank debit")}</strong><small>{new Date(`${line.txn_date}T00:00:00`).toLocaleDateString("en-MY", { day: "2-digit", month: "short", year: "numeric" })} · {line.direction}</small></span><span className="bank-amount">{line.direction === "credit" ? "+" : "−"}{money(line.amount)}</span><Status value={line.status}/></div>)}</div>}
        </section>
        <footer className="page-foot"><span>LedgerFlow <span>·</span> Selangor Properties</span><span>All changes save automatically</span></footer>
        </>}
      </div>
      {activeRun && <div className="close-bar"><div className="close-summary"><span className={`close-icon ${readyToReconcile ? "close-icon-ready" : ""}`}>{readyToReconcile ? "✓" : "↻"}</span><span><strong>{readyToReconcile ? "Ready to close" : `${reviewCount} item${reviewCount === 1 ? "" : "s"} to review`}</strong><small>{variance === 0 ? "Zero difference" : `${money(variance)} difference`} · {settledItems} of {ledgerItems} ledger entries settled</small></span></div>{activeRun.status === "open" ? <button className="button button-primary close-button" disabled={pending || !readyToReconcile} onClick={submitReconciliation}>{pending ? "Closing…" : "Mark reconciled"}</button> : <span className="closed-label">{activeRun.status === "reconciled" ? "Reconciled" : "Locked"}</span>}</div>}
    </main>

    <nav className="mobile-bottom-nav" aria-label="Workspace sections"><a href="#review"><span>⇄</span><small>Review</small></a><a href="#ledger"><span>▤</span><small>Ledger</small></a><a href="#statement"><span>▦</span><small>Bank feed</small></a><button onClick={() => setModal("people")}><span>♧</span><small>Contacts</small></button></nav>

    {modal === "run" && <Modal title="Create reconciliation run" close={close}><p className="modal-intro">Start a fresh month with an empty ledger, ready for your bank statement and records.</p><ActionForm action={createRun} close={close} submit="Create run"><Field label="Reconciliation month"><input name="period_month" type="month" required defaultValue={today().slice(0, 7)}/></Field></ActionForm></Modal>}
    {modal === "collection" && <Modal title="Add tenant collection" close={close}><p className="modal-intro">Record rent or another incoming payment for {activeRun && monthLabel(activeRun.period_month)}.</p>{tenants.length ? <ActionForm action={captureCollection} close={close} submit="Save collection"><input type="hidden" name="run_id" value={activeRun?.id}/><Field label="Tenant"><select name="tenant_id" required defaultValue=""><option value="" disabled>Select a tenant</option>{tenants.map((tenant) => <option key={tenant.id} value={tenant.id}>{tenant.name} · {money(tenant.expected_monthly)}/mo</option>)}</select></Field><div className="field-row"><Field label="Amount (MYR)"><input name="amount" type="number" min="0.01" step="0.01" placeholder="5,000.00" required/></Field><Field label="Collection date"><input name="collection_date" type="date" required defaultValue={today()}/></Field></div><Field label="Payment source"><input name="source" placeholder="Bank transfer, cash, cheque…"/></Field><Field label="Note (optional)"><input name="note" placeholder="Reference or extra detail"/></Field></ActionForm> : <div className="inline-empty">Add a tenant first from <button className="text-button" onClick={() => setModal("people")}>Vendors & tenants</button>.</div>}</Modal>}
    {modal === "payment" && <Modal title="Add vendor payment" close={close}><p className="modal-intro">Record an outgoing payment for {activeRun && monthLabel(activeRun.period_month)}.</p>{vendors.length ? <ActionForm action={capturePayment} close={close} submit="Save payment"><input type="hidden" name="run_id" value={activeRun?.id}/><Field label="Vendor"><select name="vendor_id" required defaultValue=""><option value="" disabled>Select a vendor</option>{vendors.map((vendor) => <option key={vendor.id} value={vendor.id}>{vendor.name}</option>)}</select></Field><div className="field-row"><Field label="Amount (MYR)"><input name="amount" type="number" min="0.01" step="0.01" placeholder="4,500.00" required/></Field><Field label="Payment date"><input name="payment_date" type="date" required defaultValue={today()}/></Field></div><Field label="Reference"><input name="reference" placeholder="Invoice or transfer reference"/></Field></ActionForm> : <div className="inline-empty">Add a vendor first from <button className="text-button" onClick={() => setModal("people")}>Vendors & tenants</button>.</div>}</Modal>}
    {modal === "bank" && <Modal title="Add bank statement line" close={close}><p className="modal-intro">Enter one line from your {activeRun && monthLabel(activeRun.period_month)} bank statement.</p><ActionForm action={captureBankLine} close={close} submit="Save statement line"><input type="hidden" name="run_id" value={activeRun?.id}/><div className="field-row"><Field label="Direction"><select name="direction" defaultValue="credit"><option value="credit">Credit · money in</option><option value="debit">Debit · money out</option></select></Field><Field label="Amount (MYR)"><input name="amount" type="number" min="0.01" step="0.01" required placeholder="5,000.00"/></Field></div><div className="field-row"><Field label="Transaction date"><input name="txn_date" type="date" required defaultValue={today()}/></Field><Field label="Description"><input name="description" required placeholder="Transfer or statement description"/></Field></div></ActionForm></Modal>}
    {modal?.startsWith("clear:") && (() => { const payment = payments.find((item) => item.id === modal.slice(6)); return payment ? <Modal title="Clear vendor payment" close={close}><p className="modal-intro">Link {payment.vendors?.name ?? "this payment"} ({money(payment.amount)}) to an exact matching debit.</p>{unmatchedDebits.filter((line) => Number(line.amount) === Number(payment.amount)).length ? <ActionForm action={clearPayment} close={close} submit="Clear payment"><input type="hidden" name="run_id" value={activeRun?.id}/><input type="hidden" name="payment_id" value={payment.id}/><Field label="Matching bank debit"><select name="bank_id" required defaultValue=""><option value="" disabled>Select a bank line</option>{unmatchedDebits.filter((line) => Number(line.amount) === Number(payment.amount)).map((line) => <option key={line.id} value={line.id}>{line.txn_date} · {line.description} · {money(line.amount)}</option>)}</select></Field></ActionForm> : <div className="inline-empty">No unmatched debit lines have an exact amount of {money(payment.amount)}. Add the bank statement line first.</div>}</Modal> : null; })()}
    {modal === "people" && <Modal title="Vendors & tenants" close={close}><p className="modal-intro">Manage the people and companies used when recording ledger entries.</p><div className="people-grid"><section><h3>Tenants <span className="count-pill">{tenants.length}</span></h3><div className="people-list">{tenants.map((t) => <div key={t.id}><span><strong>{t.name}</strong><small>Expected {money(t.expected_monthly)} / month</small></span></div>)}</div><ActionForm action={createTenant} close={close} submit="Add tenant"><Field label="Tenant name"><input name="name" required placeholder="e.g. Greenfield Retail"/></Field><Field label="Expected monthly rent (MYR)"><input type="number" min="0" step="0.01" name="expected_monthly" required defaultValue="0"/></Field></ActionForm></section><section><h3>Vendors <span className="count-pill">{vendors.length}</span></h3><div className="people-list">{vendors.map((v) => <div key={v.id}><span><strong>{v.name}</strong><small>{v.account_no || "Vendor"}</small></span></div>)}</div><ActionForm action={createVendor} close={close} submit="Add vendor"><Field label="Vendor name"><input name="name" required placeholder="e.g. ABC Suppliers"/></Field><Field label="Account number (optional)"><input name="account_no" placeholder="Account number"/></Field></ActionForm></section></div></Modal>}
  </div>;
}

function Metric({ title, value, icon, tone, detail }: { title: string; value: string; icon: string; tone: string; detail: string }) { return <article className="metric-card"><div className="metric-top"><span>{title}</span><span className={`metric-icon ${tone}`}>{icon}</span></div><strong className="metric-value">{value}</strong><small>{detail}</small></article>; }
